name: Full CI - Localhost Test with Playwright

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-localhost:
    name: Run E2E Test (localhost)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node + Java
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # === BACKEND ===
      - name: Build Java Backend
        working-directory: Back-end
        run: mvn clean install

      - name: Start Java Backend
        working-directory: Back-end
        run: nohup mvn spring-boot:run > ../backend.log 2>&1 &

      # === FRONTEND ===
      - name: Install frontend deps
        working-directory: Front-end
        run: npm install --legacy-peer-deps --force

      - name: Fix Browserslist warning
        working-directory: Front-end
        run: npx update-browserslist-db@latest || true

      - name: Format frontend with Prettier
        working-directory: Front-end
        run: npx prettier --write .

      - name: Start Frontend Dev Server
        working-directory: Front-end
        run: nohup npm start > ../frontend.log 2>&1 &

      # === WAIT ===
      - name: Wait for frontend & backend
        run: npx wait-on http://localhost:3000 http://localhost:8080

      # === PLAYWRIGHT TEST ===
      - name: Install test deps
        working-directory: Test_project
        run: npm ci

      - name: Install Playwright browsers
        working-directory: Test_project
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: Test_project
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: Test_project/playwright-report/
          retention-days: 30
