name: Full CI - React + Java Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Build & Test React Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Front-end
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      - name: Run Prettier to format code
        run: npx prettier --write .
        
      # ✅ Tạm tắt CSS source map để tránh lỗi postcss-calc
      - name: Build frontend (avoid postcss-calc error)
        run: GENERATE_SOURCEMAP=false npm run build

      - name: Run frontend tests
        run: npm test -- --watchAll=false
  backend:
    name: Build & Test Java Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Back-end
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test backend with Maven
        run: mvn clean install

  playwright:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    defaults:
      run:
        working-directory: Test_project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
